services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: Ats 
      POSTGRES_PASSWORD: ATS_DB_PASSWORD 
      POSTGRES_DB: ATS_DB 
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
