services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: Ats 
      POSTGRES_PASSWORD: ATS_DB_PASSWORD 
      POSTGRES_DB: ATS_DB 
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: Ats
      MINIO_ROOT_PASSWORD: ATS_DB_PASSWORD
    ports:
      - '9000:9000'   # API
      - '9001:9001'   # web console
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  postgres_data:
  minio_data:
